# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Initialise boosting with chosen accelerator hardware (x86, AVX, FMA)
#' 
#' @param data Matrix
#' @param stepno Amount of steps
#' @param mode_ Accelerator mode (0: x86, 1: FMA, 2: AVX)
#' @return none
cpp_filter_base <- function(data, stepno = 20L, mode_ = 2L) {
    invisible(.Call('_netboost_filter_base', PACKAGE = 'netboost', data, stepno, mode_))
}

#' @title Boosting cleanup (required to free memory)
#' 
#' @return none
cpp_filter_end <- function() {
    invisible(.Call('_netboost_filter_end', PACKAGE = 'netboost'))
}

#' @title Single boosting step
#' 
#' @details Must be initialised before using \code{\link{cpp_filter_base}}
#' 
#' @param col_y Row in data matrix
#' @return integer vector
cpp_filter_step <- function(col_y) {
    .Call('_netboost_rcpp_filter_step', PACKAGE = 'netboost', col_y)
}

#' @title Function to calcutate distance
#' @details
#' Steps:
#'   1. - Sequential preparation of index and partner caches per value in filter
#'   2. - Parallel calculation of the distances with cached vectors
#'
#' @param filter Filter matrix
#' @param adjacency Vector
#' @return numeric vector
cpp_dist_tom <- function(filter, adjacency) {
    .Call('_netboost_dist_tom', PACKAGE = 'netboost', filter, adjacency)
}

#' @title In-memory MC-UPGMA clustering (single round)
#'
#' @description Portable reimplementation of the sparse average-linkage
#'   (UPGMA) clustering performed by netboost. Missing pairs are treated as
#'   distance \code{max_distance}; merging proceeds in order of increasing
#'   distance (ties broken by the largest cluster-id pair) until no edge with
#'   distance <= \code{max_distance} remains, yielding a forest.
#'
#' @param low Integer vector, smaller cluster id of each input edge (1-based).
#' @param high Integer vector, larger cluster id of each input edge (1-based).
#' @param dist Numeric vector of edge distances (in [0, max_distance]).
#' @param max_singleton Numeric. Maximum singleton id; new (merged) cluster ids
#'   start at \code{max_singleton + 1}.
#' @param max_distance Numeric. Upper distance bound (psi); also the distance
#'   assigned to missing pairs.
#' @return Numeric matrix with columns cluster_id1, cluster_id2, distance,
#'   cluster_id3 (one row per merge, in merge order).
cpp_mcupgma <- function(low, high, dist, max_singleton, max_distance) {
    .Call('_netboost_cpp_mcupgma', PACKAGE = 'netboost', low, high, dist, max_singleton, max_distance)
}

#' @title Tree search.
#' @name cpp_tree_search
#' 
#' @description
#' Constraint: IDs 0 <= x (Integer)
#' 
#' @backref src/tree_sort.cpp 
#'
#' @param netboost_forest Input-matrix (4 columns, ids in colum 0,1,3)
#' @return List
#'
cpp_tree_search <- function(netboost_forest) {
    .Call('_netboost_tree_search', PACKAGE = 'netboost', netboost_forest)
}

